apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-db-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    template:
      engineVersion: v2
      data:
        credentials: |
          db_con="{{ .db_url }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"

  data:
    - secretKey: db_url
      remoteRef:
        key: "mysql-credentials" # Nom du secret dans AWS Secret Manager
        property: "url" # Propriété JSON dans le secret
    - secretKey: db_username
      remoteRef:
        key: "mysql-credentials"
        property: "username"
    - secretKey: db_password
      remoteRef:
        key: "mysql-credentials"
        property: "password"
